# Generated by Django 5.2 on 2025-05-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_user_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='pages.course'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
