# Generated by Django 5.2 on 2025-05-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='Instructor_image',
            field=models.ImageField(blank=True, null=True, upload_to='instructor_images/'),
        ),
    ]
