# Generated by Django 5.2 on 2025-05-02 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_instructorprofile_instructor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.instructorprofile'),
        ),
    ]
