# Generated by Django 5.2 on 2025-05-02 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_coursecontent_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='pages.course'),
        ),
    ]
