# Generated by Django 5.2 on 2025-05-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_instructorprofile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='num_studenta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
