# Generated by Django 5.2 on 2025-05-03 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_instructorprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
