# Generated by Django 5.2 on 2025-05-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_instructorprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='user',
        ),
    ]
